#!/bin/sh

cwd=$(pwd)

show_done_message() {
  echo "✓ Done"
  echo
}

echo "Installing python plugin support for neovim..."
pip install --upgrade neovim
show_done_message

echo "Symlinking neovim config from vim"
ln -sf ~/.vim ~/.config/nvim
ln -sf ~/.vimrc ~/.config/nvim/init.vim
show_done_message

echo "Installing vim plugins"
nvim +PlugInstall +qa
show_done_message

echo 'Installing Nerd Font: Source Code Pro'
tmpdir="$HOME/.dotfiles/tmp"
path="${tmpdir}/SourceCodePro.zip"
if [ -f $path ]
then
  show_done_message
else
  mkdir $tmpdir
  wget https://github.com/ryanoasis/nerd-fonts/releases/download/v1.0.0/SourceCodePro.zip -O "${path}"
  unzip $path -d $tmpdir
  cp ${tmpdir}/Sauce* $HOME/Library/Fonts
  cd $cwd
  show_done_message
fi
