#!/bin/sh

cwd=$(pwd)

show_done_message() {
  echo "✓ Done"
  echo
}

show_nothing_to_do_message() {
  echo "✓ Nothing to do"
  echo
}

echo "Symlinking neovim config from vim"
ln -sf ~/.vim ~/.config/nvim
ln -sf ~/.vimrc ~/.config/nvim/init.vim
show_done_message

echo "Checking for tmux plugin manager"
if [ -d "$HOME/.tmux/plugins/tpm" ]
then
  show_nothing_to_do_message
else
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins
  show_done_message
fi

echo "Enabling italics in tmux"
tic ~/terminal/xterm-256color.terminfo
tic ~/terminal/tmux-256color-italic.terminfo
show_done_message

echo "Installing vim plugins"
nvim +PlugUpdate
show_done_message

echo 'Installing Nerd Font: Source Code Pro'
tmpdir="$HOME/.dotfiles/tmp"
path="${tmpdir}/SourceCodePro.zip"
if [ -f $path ]
then
  show_nothing_to_do_message
else
  mkdir $tmpdir
  wget https://github.com/ryanoasis/nerd-fonts/releases/download/v1.0.0/SourceCodePro.zip -O "${path}"
  unzip $path -d $tmpdir
  cp ${tmpdir}/Sauce* $HOME/Library/Fonts
  cd $cwd
  show_done_message
fi
